[package]
name = "noble6"
version = "0.1.0"
authors = ["zero.qn <zero.qn@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo = { git = "https://github.com/ebfull/halo" }
sha2 = "0.8.1"
